version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/arm64
    network_mode: host  # Add this line
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && node main.js"

  viaproxy: #use this service to connect to an unsupported minecraft server versions. more info: ./services/viaproxy/README.md
    image: ghcr.io/viaversion/viaproxy:latest
    volumes:
      - ./services/viaproxy:/app/run
    ports:
      - "25568:25568"
    profiles:
      - viaproxy
