FROM node:22
RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip \
        build-essential \
        libx11-dev \
        libxi-dev \
        libxext-dev \
        libxrandr-dev \
        libxss1 \
        libasound2-dev \
        libgl1-mesa-dev \
        libglu1-mesa-dev \
        mesa-common-dev \
        libglew-dev \
        libglfw3-dev \
        xorg-dev && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app